services:
  # Web service for the dashboard
  - type: web
    name: api-monitor-dashboard
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.dashboard:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: api-monitor-db
          property: connectionString

  # Background worker for monitoring
  - type: worker
    name: api-monitor-worker
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/monitor.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: api-monitor-db
          property: connectionString

databases:
  - name: api-monitor-db
    plan: free
    databaseName: apimonitor
    user: apimonitor
