services:
  # Web service for the dashboard
  - type: web
    name: api-monitor-dashboard
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_PATH
        value: /tmp/api_monitor.db
      - key: FLASK_ENV
        value: production

  # Background worker for monitoring
  - type: worker
    name: api-monitor-worker
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/monitor.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_PATH
        value: /tmp/api_monitor.db
