services:
  # Single web service that runs both dashboard and monitoring
  - type: web
    name: api-monitor
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.wsgi:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_PATH
        value: /tmp/api_monitor.db
      - key: FLASK_ENV
        value: production
